name: Unit tests
on: [push, pull_request]
jobs:
  test:
    name: "Run tests"
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.0', '3.1', '3.2', '3.3', 'head', 'jruby-9.4', 'jruby-head', 'truffleruby' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        sudo apt-get install libnotify4
        bundle install --jobs 4 --retry 3
        bundle exec rake test
